### PR TITLE
display the "listbar" to access playlist

### PR DESCRIPTION
**Pull request by thornomad**
the list bar wasn't being displayed with the video playlist shortcake ... added it (maybe new setting since you upgraded jwplayer)

### CODE REVIEW

**Comment by elizoller** [comment]
Ah, thanks. As far as I know listbar isn't needed/not used in Jwplayer 7.

**Comment by thornomad** [comment]
Oh yuck you are right: they did away with it entirely and now have it as like a pop-up.  I see a bunch of people asking for it back.  The toolkit is using version 6 though, right?  

The version 7 playlist isn't as obvious ... I like 6 better.

**Comment by elizoller** [comment]
I have 7 hanging out in a separate branch right now because of that issue with the networking on the JavaScript file I mentioned.

**Comment by nestochan** [comment]
version 7 is triggering a security filter associated with ThreatID 30419... to use this version will require a whitelist exemption to allow JWP7 out of the datacenter. This exemption has to be vetted by Office of Info Security -- so stay tuned for news on that...

**Comment by elizoller** [comment]
Great. Thanks!

**Pull request merged**
